### ISSUE TITLE
add more space to placeholder text

### ISSUE THREAD

**Issue by jessej-samuel** [jaydeepdey03/youtube-clone#5]
![image](https://user-images.githubusercontent.com/72020411/193626639-130b5ad0-efba-4a86-bb88-7e470dfa5a91.png)
 Adding more space would be better like this ⬇️ 
 
![image](https://user-images.githubusercontent.com/72020411/193626837-d819cd0b-0717-49dd-bbc7-e8b7dc41ab85.png)

**Comment by jaydeepdey03** [comment]
Go Ahead @jessej-samuel.

**Comment by jessej-samuel** [comment]
@jaydeepdey03 #6  fixes this issue
