### ISSUE TITLE
make a better readme

### ISSUE THREAD

**Issue by jessej-samuel** [jaydeepdey03/youtube-clone#7]
I could make a better readme with pictures, tech stack used and other cool stuff.
It would be more appealing and allows the user to know more about the project 😀

**Comment by jaydeepdey03** [comment]
Go ahead @jessej-samuel

**Comment by jessej-samuel** [comment]
Also you shud consider adding a LICENSE.md

**Comment by jessej-samuel** [comment]
Btw check the pr abov 👆
